export type Lang = 'fr' | 'en';

/** `frontend` is served at `/`, `cyber` at `/cyber`. */
export type Profile = 'frontend' | 'cyber';

export interface Skill {
  id: string;
  name: string;
  icon: string;
  /** What backs the skill, not a self-assigned score. */
  label: string;
  /** Key of the owning group; the set of groups is declared per profile. */
  group: string;
}

/** A titled band in the skills section. Order = display order. */
export interface SkillGroup {
  key: string;
  heading: string;
}

export interface Experience {
  id: string;
  year: string;
  company: string;
  role: string;
}

export interface Project {
  id: string;
  number: string;
  name: string;
  description: string;
  tags: string[];
  link?: string;
  category?: 'personal' | 'school' | 'professional';
  preview?: string;
  modal?: boolean;
}

/** Headline number shown as a stat tile above the case-study prose. */
export interface CaseStudyMetric {
  /** "12", "~40%", "3 → 1" */
  value: string;
  /** What it counts, in a few words. */
  label: string;
}

export interface CaseStudy {
  title: string;
  kicker: string;
  role: string;
  duration: string;
  /** Optional: only fill in with real figures. */
  metrics?: CaseStudyMetric[];
  context: string;
  challenge: string;
  approach: string[];
  results: string[];
  stack: string[];
}

/** Section headings and fallback copy for the case-study modal. */
export interface CaseStudyHeadings {
  context: string;
  challenge: string;
  approach: string;
  results: string;
  stack: string;
  soon: string;
}

export interface ContactLink {
  id: string;
  label: string;
  url: string;
  external?: boolean;
  /** Action verb shown as the row's call to action (e.g. "Écrire", "Ouvrir"). */
  cta: string;
}

export interface Video {
  id: string;
  title: string;
  filename: string;
  description?: string;
  /** Poster frame under `public/`, generated by scripts/optimize-media.sh. */
  poster?: string;
}

export interface FocusPillar {
  id: string;
  icon: string;
  title: string;
  description: string;
}

export interface PortfolioContent {
  name: string;
  tagline: string;
  heroJobTitle: string;
  heroValue: string;
  /** Apprenticeship on /cyber, CDI on /. */
  availabilityBanner: string;
  availabilityDetail: string;
  yearsExp: string;
  aboutTitle: string;
  aboutDescription: string;
  contactEmail: string;
  contactLocation: string;
  contactAvailability: string;
}

export interface UIStrings {
  navLinks: Array<{ label: string; href: string }>;
  navAvailability: string;
  langToggleLabel: string;
  heroBadge: string;
  heroCtaWork: string;
  heroCtaCv: string;
  aboutLabel: string;
  aboutJourneyLabel: string;
  skillsLabel: string;
  projectsLabel: string;
  projectsKicker: string;
  projectsSummary: string;
  projectsShown: string;
  /** Shown when the active filter matches no project. */
  projectsEmpty: string;
  projectsIssueLabel: string;
  filterAll: string;
  filterProfessional: string;
  filterPersonal: string;
  filterTechnical: string;
  categoryStudio: string;
  categoryPersonal: string;
  categoryLab: string;
  categoryFeature: string;
  /** Call to action on project cards that open an external link. */
  projectCta: string;
  /** Call to action on project cards that open the detail modal. */
  projectCtaDetails: string;
  /** Shown in place of a screenshot on client work that cannot be shown. */
  projectConfidential: string;
  focusLabel: string;
  videosLabel: string;
  videosHeading: string;
  videosSubtitle: string;
  contactLabel: string;
  contactTitle: string;
  footerRole: string;
  /** Cross-link to the other positioning. Absent on frontend. */
  otherProfileLabel?: string;
  otherProfileHref?: string;

  // Assistive-technology strings, kept here so content.test.ts covers them.
  skipToContent: string;
  menuOpen: string;
  menuClose: string;
  menuToggleLabel: string;
  menuCloseLabel: string;
  closeModalLabel: string;
  previousVideoLabel: string;
  nextVideoLabel: string;
  projectFiltersLabel: string;
}

export interface LocalizedContent {
  profile: Profile;
  portfolio: PortfolioContent;
  skills: Skill[];
  skillGroups: SkillGroup[];
  experience: Experience[];
  projects: Project[];
  /** Keyed by project id; only `modal: true` projects have an entry. */
  caseStudies: Record<string, CaseStudy>;
  caseStudyHeadings: CaseStudyHeadings;
  videos: Video[];
  contactLinks: ContactLink[];
  /** CV to download for this positioning. */
  cvUrl: string;
  focusPillars: FocusPillar[];
  marquee: string[];
  ui: UIStrings;
}
