#!/usr/bin/env node
/**
 * Vendor Syne and Space Mono into public/fonts/ and generate the @font-face
 * rules that point at them.
 *
 *     node scripts/vendor-fonts.mjs
 *
 * The site used to link fonts.googleapis.com from <head>. That is a
 * render-blocking stylesheet on a third-party origin: a DNS lookup, a TLS
 * handshake and a round trip before the first paint, on the critical path,
 * every visit. These two families *are* the design system, so they are worth
 * serving from our own origin next to everything else.
 *
 * Only the latin and latin-ext subsets are kept — the site is French and
 * English, and Google serves nine subsets by default.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'public/fonts');
const CSS_OUT = resolve(ROOT, 'src/styles/fonts.css');

const SOURCE =
  'https://fonts.googleapis.com/css2?family=Syne:wght@400;700;800&family=Space+Mono:wght@400;700&display=swap';

// woff2 is only offered to a browser UA; a bare fetch is served ttf.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const KEEP = new Set(['latin', 'latin-ext']);

const css = await fetch(SOURCE, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts responded ${r.status}`);
  return r.text();
});

await mkdir(OUT_DIR, { recursive: true });

// Each @font-face is preceded by a /* subset */ comment.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (blocks.length === 0) throw new Error('no @font-face blocks parsed');

const rules = [];
let downloaded = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;

  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  if (!url || !family || !weight) throw new Error(`could not parse block:\n${block}`);

  const filename = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  await writeFile(resolve(OUT_DIR, filename), bytes);
  downloaded += bytes.length;
  console.log(`public/fonts/${filename}  ${Math.round(bytes.length / 1024)} KB`);

  rules.push(block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${filename}')`));
}

const header = `/*
 * Generated by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * Self-hosted so the first paint does not wait on a third-party origin.
 * Only latin and latin-ext are vendored; the site is French and English.
 */
`;

await writeFile(CSS_OUT, `${header}\n${rules.join('\n\n')}\n`);
console.log(
  `\nwrote ${rules.length} @font-face rules to src/styles/fonts.css ` +
    `(${Math.round(downloaded / 1024)} KB of woff2)`
);
